import os
from datetime import datetime
from PIL import Image as PILImage
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def get_scaled_image_dims(image_path, max_width, max_height):
    """Calculates dimensions maintaining aspect ratio, or returns max_width/max_height as default."""
    if not image_path or not os.path.exists(image_path):
        return max_width, max_height
    try:
        with PILImage.open(image_path) as img:
            w, h = img.size
            aspect = w / h
            if w > max_width or h > max_height:
                if aspect > max_width / max_height:
                    # Width limited
                    new_w = max_width
                    new_h = int(max_width / aspect)
                else:
                    # Height limited
                    new_h = max_height
                    new_w = int(max_height * aspect)
                return new_w, new_h
            return w, h
    except Exception:
        return max_width, max_height

def add_footer(canvas, doc):
    """Callback to draw a clean footer on the page."""
    canvas.saveState()
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.HexColor('#64748b'))
    
    # Draw line above footer
    canvas.setStrokeColor(colors.HexColor('#e2e8f0'))
    canvas.setLineWidth(0.75)
    canvas.line(36, 45, 559.27, 45)
    
    # Draw text
    canvas.drawString(36, 30, "Generated by Vision Inspection System")
    canvas.drawRightString(559.27, 30, f"Page {doc.page} of 1")
    canvas.restoreState()

def create_inspection_report(
    serial_number,
    model_name,
    status,
    date_str,
    time_str,
    traceability_id,
    front_image_path,
    back_image_path,
    ocr_serial,
    confidence,
    defects=None,
    defect_image_path=None,
    output_path=None
):
    """Generates a professional A4 PDF inspection report."""
    
    # Resolve default output path if not provided
    if output_path is None:
        today_dir = datetime.now().strftime("%Y-%m-%d")
        report_dir = os.path.join("Reports", today_dir)
        os.makedirs(report_dir, exist_ok=True)
        output_path = os.path.join(report_dir, f"{serial_number}.pdf")
    else:
        # Ensure parent directory of output_path exists
        parent_dir = os.path.dirname(output_path)
        if parent_dir:
            os.makedirs(parent_dir, exist_ok=True)

    # Initialize Document with A4 dimensions (595.27 x 841.89 pt) and 36pt margins
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Custom Paragraph Styles
    title_style = ParagraphStyle(
        'ReportTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=22,
        leading=26,
        textColor=colors.HexColor('#1a365d'),
        alignment=1, # Center
        spaceAfter=15
    )
    
    header_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=14,
        textColor=colors.HexColor('#1a365d'),
    )
    
    cell_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor('#1e293b')
    )
    
    caption_style = ParagraphStyle(
        'ImageCaption',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=12,
        alignment=1, # Center
        textColor=colors.HexColor('#475569')
    )
    
    story = []
    
    # ---------------------------------------------------------
    # 1. Report Title
    # ---------------------------------------------------------
    story.append(Paragraph("VISION INSPECTION REPORT", title_style))
    story.append(Spacer(1, 10))
    
    # Helper to generate section headers
    def make_section_header(title):
        t = Table([[Paragraph(title, header_style)]], colWidths=[523.27])
        t.setStyle(TableStyle([
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('LINEBELOW', (0,0), (-1,-1), 1.5, colors.HexColor('#1a365d')),
        ]))
        return t

    # ---------------------------------------------------------
    # 2. Inspection Details
    # ---------------------------------------------------------
    story.append(make_section_header("Inspection Details"))
    story.append(Spacer(1, 8))
    
    status_color = '#10b981' if status.upper() == 'PASS' else '#ef4444'
    status_html = f"<font color='{status_color}'><b>{status.upper()}</b></font>"
    
    details_data = [
        [
            Paragraph("<b>Serial Number:</b>", cell_style), Paragraph(serial_number, cell_style),
            Paragraph("<b>Inspection Status:</b>", cell_style), Paragraph(status_html, cell_style)
        ],
        [
            Paragraph("<b>Inspection Date:</b>", cell_style), Paragraph(date_str, cell_style),
            Paragraph("<b>Inspection Time:</b>", cell_style), Paragraph(time_str, cell_style)
        ]
    ]
    
    details_table = Table(details_data, colWidths=[120, 141.63, 120, 141.64])
    details_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#f8fafc')),
        ('BACKGROUND', (2,0), (2,-1), colors.HexColor('#f8fafc')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('PADDING', (0,0), (-1,-1), 6),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(details_table)
    story.append(Spacer(1, 15))
    
    # ---------------------------------------------------------
    # 3. Inspection Images
    # ---------------------------------------------------------
    story.append(make_section_header("Inspection Images"))
    story.append(Spacer(1, 10))
    
    # Scaled dimensions for the two side-by-side images (fit in 240 x 150 area)
    max_w, max_h = 240, 150
    w_l, h_l = get_scaled_image_dims(front_image_path, max_w, max_h)
    w_r, h_r = get_scaled_image_dims(back_image_path, max_w, max_h)
    
    # Flowables for images or placeholders if not found
    if front_image_path and os.path.exists(front_image_path):
        img_l = Image(front_image_path, width=w_l, height=h_l)
    else:
        # Create a text placeholder
        img_l = Paragraph("<font color='#ef4444'>[Front Image Not Found]</font>", caption_style)
        w_l, h_l = max_w, 100
        
    if back_image_path and os.path.exists(back_image_path):
        img_r = Image(back_image_path, width=w_r, height=h_r)
    else:
        img_r = Paragraph("<font color='#ef4444'>[Back Image Not Found]</font>", caption_style)
        w_r, h_r = max_w, 100

    # Wrap images in single-cell tables for a neat border
    img_l_table = Table([[img_l]], colWidths=[w_l], rowHeights=[h_l] if front_image_path and os.path.exists(front_image_path) else [100])
    img_l_table.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 0.75, colors.HexColor('#94a3b8')),
        ('PADDING', (0,0), (-1,-1), 2),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    
    img_r_table = Table([[img_r]], colWidths=[w_r], rowHeights=[h_r] if back_image_path and os.path.exists(back_image_path) else [100])
    img_r_table.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 0.75, colors.HexColor('#94a3b8')),
        ('PADDING', (0,0), (-1,-1), 2),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    
    # Side-by-side images container table
    image_container_data = [
        [img_l_table, img_r_table],
        [Paragraph("<b>Front View</b><br/>Front Image", caption_style),
         Paragraph("<b>Back View</b><br/>Back Image", caption_style)]
    ]
    
    img_container_table = Table(image_container_data, colWidths=[261.63, 261.64])
    img_container_table.setStyle(TableStyle([
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,1), (-1,1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
    ]))
    
    story.append(img_container_table)
    story.append(Spacer(1, 15))

    # ---------------------------------------------------------
    # 3b. Defect Analysis Image (only when defects detected)
    # ---------------------------------------------------------
    # Show the annotated front frame that has all defect bounding boxes/masks drawn on it.
    # This is the 3rd image in the report: front (clean) + back (clean) + defect annotated.
    actual_defects = [d for d in (defects or []) if d not in ("holes_missing", "serial_missing")]
    has_visual_defects = bool(actual_defects)

    if has_visual_defects and defect_image_path and os.path.exists(defect_image_path):
        story.append(make_section_header("Defect Analysis"))
        story.append(Spacer(1, 10))

        # Full-width defect image (max 480 wide x 300 tall)
        max_dw, max_dh = 480, 300
        dw, dh = get_scaled_image_dims(defect_image_path, max_dw, max_dh)
        defect_img = Image(defect_image_path, width=dw, height=dh)

        defect_img_table = Table([[defect_img]], colWidths=[dw], rowHeights=[dh])
        defect_img_table.setStyle(TableStyle([
            ('BOX', (0,0), (-1,-1), 1.5, colors.HexColor('#ef4444')),
            ('PADDING', (0,0), (-1,-1), 3),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))

        defect_label = ", ".join(d.replace("_", " ").title() for d in actual_defects)
        defect_caption = Paragraph(
            f"<b>Detected Defects:</b> <font color='#ef4444'>{defect_label}</font><br/>"
            f"Annotated front frame — defect regions highlighted with bounding boxes and masks",
            caption_style
        )

        # Center the image horizontally on the page
        defect_wrapper = Table([[defect_img_table]], colWidths=[523.27])
        defect_wrapper.setStyle(TableStyle([
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))

        story.append(defect_wrapper)
        story.append(Spacer(1, 6))
        story.append(defect_caption)
        story.append(Spacer(1, 15))
    
    # ---------------------------------------------------------
    # 4. Inspection Result Details
    # ---------------------------------------------------------
    story.append(make_section_header("Inspection Result"))
    story.append(Spacer(1, 10))
    
    # Large Badge for PASS/FAIL status
    badge_bg = '#d1e7dd' if status.upper() == 'PASS' else '#f8d7da'
    badge_fg = '#0f5132' if status.upper() == 'PASS' else '#842029'
    
    badge_text_style = ParagraphStyle(
        'ResultBadgeText',
        fontName='Helvetica-Bold',
        fontSize=26,
        leading=30,
        alignment=1, # Center
        textColor=colors.HexColor(badge_fg)
    )
    
    badge_table = Table([[Paragraph(status.upper(), badge_text_style)]], colWidths=[180], rowHeights=[60])
    badge_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor(badge_bg)),
        ('BOX', (0,0), (-1,-1), 1.5, colors.HexColor(badge_fg)),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
    ]))
    
    # Format confidence score
    conf_str = f"{confidence}"
    if isinstance(confidence, (int, float)):
        conf_str = f"{confidence:.2f}%"
    elif isinstance(confidence, str) and not confidence.endswith('%'):
        try:
            conf_str = f"{float(confidence):.2f}%"
        except ValueError:
            pass
            
    result_details = [
        [Paragraph("<b>Product Serial:</b>", cell_style), Paragraph(serial_number, cell_style)],
        [Paragraph("<b>Confidence:</b>", cell_style), Paragraph(conf_str, cell_style)],
        [Paragraph("<b>Inspection Timestamp:</b>", cell_style), Paragraph(f"{date_str} {time_str}", cell_style)]
    ]
    
    result_details_table = Table(result_details, colWidths=[140, 183.27])
    result_details_table.setStyle(TableStyle([
        ('LINEBELOW', (0,0), (-1,-2), 0.5, colors.HexColor('#e2e8f0')),
        ('PADDING', (0,0), (-1,-1), 4),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    
    result_layout = Table([[badge_table, result_details_table]], colWidths=[200, 323.27])
    result_layout.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('ALIGN', (0,0), (0,0), 'CENTER'),
        ('LEFTPADDING', (1,0), (1,0), 20),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
        ('LEFTPADDING', (0,0), (0,0), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
    ]))
    
    story.append(result_layout)
    
    if defects:
        defect_str = ", ".join(defects).replace('_', ' ')
        defect_text = f"<font color='#ef4444'><b>Defects detected : {defect_str}</b></font>"
        story.append(Spacer(1, 10))
        story.append(Paragraph(defect_text, ParagraphStyle(
            'DefectText',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=12,
            leading=16,
            alignment=1 # Center
        )))
    
    # Build document
    doc.build(story, onFirstPage=add_footer)
    return output_path

if __name__ == "__main__":
    # Test generation with mock data and one of the local images
    print("Generating sample report...")
    front_img = "WhatsApp Image 2026-07-22 at 9.55.38 AM.jpeg"
    back_img = "WhatsApp Image 2026-07-22 at 9.56.24 AM.jpeg"
    
    out_file = create_inspection_report(
        serial_number="000011",
        model_name="CPIP Cam",
        status="PASS",
        date_str="2026-07-22",
        time_str="10:45:32",
        traceability_id="TRC000012",
        front_image_path=front_img,
        back_image_path=back_img,
        ocr_serial="000011",
        confidence=99.82,
        defects=["dent", "serial_missing"],
        output_path="Reports/2026-07-22/000011.pdf"
    )
    print(f"Sample report generated successfully at: {out_file}")
